### PR TITLE
Bump to ECS 4

### PR DESCRIPTION
**Pull request by TomasVotruba**
After https://github.com/Symplify/Symplify/pull/818 the ECS **is now available for Symfony 3.4**.
So [Sylius](https://github.com/Sylius/Sylius/blob/ef826fee26a21faa5a2a57016b32c2829117b929/composer.json#L61) can use ECS 4 as well.

## Changes in ECS

- Neon switched to Yaml: https://www.tomasvotruba.cz/blog/2018/03/12/neon-vs-yaml-and-how-to-migrate-between-them

## Todo before Merge

- [x] test it on https://github.com/Sylius/Sylius/ first - https://github.com/Sylius/Sylius/pull/9400
- [x] use stable ECS - https://github.com/Symplify/EasyCodingStandard/releases/tag/v4.2.2

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge

**Comment by pamil** [comment]
Thanks Tomas!

**Comment by TomasVotruba** [comment]
Happy to help!

**Comment by pamil** [comment]
I'll tag a new release in a second.

**Comment by pamil** [comment]
2.0.0 released 🎉

**Pull request merged**
